Add CI: Format, Lint & Weak Type Check
near/gas-station-event-indexer pull request #6
Opened 2024-04-21 20:46 UTC by bh2smith

This PR adds a workflow file that runs black pylint & mypy.

The reason for the invasive change on the primary function was the deep nesting compliant from pylint. Before there were three nested loops (on shards, receipt_execution_outcomes, logs) which has been broken into three `process_XXX` methods.

Technically it would be possible to introduce this change without the big refactor (by simply adding a pylint disable to this particular message

```
R1702: Too many nested blocks (7/5) (too-many-nested-blocks)
``` 

and following up with another PR that addresses this only.

If accepted, I would proceed with 
1. adding a more strict type check (i.e. mypy --strict) and fixing the 
<details>
<summary>related issues</summary>

```sh
gas_station_event_indexer.py:23: error: Function is missing a return type annotation  [no-untyped-def]
gas_station_event_indexer.py:73: error: Missing type parameters for generic type "dict"  [type-arg]
gas_station_event_indexer.py:86: error: Missing type parameters for generic type "dict"  [type-arg]
gas_station_event_indexer.py:104: error: Returning Any from function declared to return "dict[Any, Any] | None"  [no-any-return]
gas_station_event_indexer.py:107: error: Function is missing a return type annotation  [no-untyped-def]
gas_station_event_indexer.py:112: error: Function is missing a return type annotation  [no-untyped-def]
gas_station_event_indexer.py:121: error: Function is missing a return type annotation  [no-untyped-def]
gas_station_event_indexer.py:131: error: Missing type parameters for generic type "dict"  [type-arg]
gas_station_event_indexer.py:153: error: Function is missing a return type annotation  [no-untyped-def]
gas_station_event_indexer.py:153: error: Missing type parameters for generic type "dict"  [type-arg]
gas_station_event_indexer.py:169: error: Function is missing a return type annotation  [no-untyped-def]
```
</details>
2. Adding unit tests to the new smaller methods.

2024-04-22 17:40 UTC, anthony-near requested changes
overall looks good. Just add versioning for packages added to requirements.txt

2024-04-22 17:40 UTC, anthony-near commented on requirements.txt
> +black
please include the versions for the new requirements.

2024-04-23 07:50 UTC, bh2smith commented on requirements.txt
> +black
Done.

2024-04-23 07:51 UTC, bh2smith commented on requirements.txt
> +types-requests>=2.31.0.20240406
```suggestion
types-requests>=2.31.0.20240406

```

2024-04-23 12:59 UTC, anthony-near approved these changes

2024-04-23 12:59 UTC, merged